[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python jupiter_elite_bot_complete.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
